//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shadowshot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shadowshot.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a screenshot of active window and save to clipboard.
        /// </summary>
        public static string ActiveWindowToClipboard {
            get {
                return ResourceManager.GetString("ActiveWindowToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a screenshot of active window and save to clipboard:.
        /// </summary>
        public static string ActiveWindowToClipboardColon {
            get {
                return ResourceManager.GetString("ActiveWindowToClipboardColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a screenshot of active window and save to desktop.
        /// </summary>
        public static string ActiveWindowToDesktop {
            get {
                return ResourceManager.GetString("ActiveWindowToDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a screenshot of active window and save to desktop:.
        /// </summary>
        public static string ActiveWindowToDesktopColon {
            get {
                return ResourceManager.GetString("ActiveWindowToDesktopColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a screenshot of entire screen and save to clipboard.
        /// </summary>
        public static string EntireScreenToClipboard {
            get {
                return ResourceManager.GetString("EntireScreenToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a screenshot of entire screen and save to clipboard:.
        /// </summary>
        public static string EntireScreenToClipboardColon {
            get {
                return ResourceManager.GetString("EntireScreenToClipboardColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a screenshot of entire screen and save to desktop.
        /// </summary>
        public static string EntireScreenToDesktop {
            get {
                return ResourceManager.GetString("EntireScreenToDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a screenshot of entire screen and save to desktop:.
        /// </summary>
        public static string EntireScreenToDesktopColon {
            get {
                return ResourceManager.GetString("EntireScreenToDesktopColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Shot {0:yyyy-MM-dd} at {0:h.mm.ss tt}.png.
        /// </summary>
        public static string FilenameFormat {
            get {
                return ResourceManager.GetString("FilenameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Shadowshot when system starts.
        /// </summary>
        public static string IsAutoStart {
            get {
                return ResourceManager.GetString("IsAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Shortcuts.
        /// </summary>
        public static string KeyboardShortcuts {
            get {
                return ResourceManager.GetString("KeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2017-2018 Victorique Ko. All rights reserved..
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadowshot is running in the background..
        /// </summary>
        public static string RunningInTheBackground {
            get {
                return ResourceManager.GetString("RunningInTheBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadowshot.
        /// </summary>
        public static string Shadowshot {
            get {
                return ResourceManager.GetString("Shadowshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string VersionFormat {
            get {
                return ResourceManager.GetString("VersionFormat", resourceCulture);
            }
        }
    }
}
